/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScramjetSplatRouteImport } from './routes/scramjet/$'
import { Route as ApiPublicGSplatRouteImport } from './routes/api/public/g/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScramjetSplatRoute = ScramjetSplatRouteImport.update({
  id: '/scramjet/$',
  path: '/scramjet/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGSplatRoute = ApiPublicGSplatRouteImport.update({
  id: '/api/public/g/$',
  path: '/api/public/g/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scramjet/$': typeof ScramjetSplatRoute
  '/api/public/g/$': typeof ApiPublicGSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scramjet/$': typeof ScramjetSplatRoute
  '/api/public/g/$': typeof ApiPublicGSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scramjet/$': typeof ScramjetSplatRoute
  '/api/public/g/$': typeof ApiPublicGSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scramjet/$' | '/api/public/g/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scramjet/$' | '/api/public/g/$'
  id: '__root__' | '/' | '/scramjet/$' | '/api/public/g/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScramjetSplatRoute: typeof ScramjetSplatRoute
  ApiPublicGSplatRoute: typeof ApiPublicGSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scramjet/$': {
      id: '/scramjet/$'
      path: '/scramjet/$'
      fullPath: '/scramjet/$'
      preLoaderRoute: typeof ScramjetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/g/$': {
      id: '/api/public/g/$'
      path: '/api/public/g/$'
      fullPath: '/api/public/g/$'
      preLoaderRoute: typeof ApiPublicGSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScramjetSplatRoute: ScramjetSplatRoute,
  ApiPublicGSplatRoute: ApiPublicGSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
